### ISSUE TITLE
Hacker News button totally down.

### ISSUE THREAD

**Issue by tylermenezes** [segment-boneyard/hn-button.com#2]
Just getting Heroku errors now :(

Are you using the api.hnsearch.com API on ThriftDB? It seem like it went down a few days ago, and all the alternative like buttons seem to have failed for that reason.

**Comment by Jolg42** [comment]
Indeed … The Heroku application is down :/

**Comment by ianstormtaylor** [comment]
sorry guys! looking into this now

**Comment by tylermenezes** [comment]
No problem, thanks for the support :)

**Comment by ianstormtaylor** [comment]
should be up again! updated to the new search api, and made it so that errors in the api lookups now just default to the "submit" version of the button in the future. let me know if you notice any weirdness

**Comment by Jolg42** [comment]
@ianstormtaylor :+1: Thank You ! The button is back on http://www.rudebaguette.com/ !

**Comment by ianstormtaylor** [comment]
sweet! i need to update the facebook styles later :$ might wanna go with hn defaults for now
